config/routes.rb
Rails.application.routes.draw do

  get '/:token/confirm_email/', :to => "users#confirm_email", as: 'confirm_email'

  devise_for :users , controllers: {
    registrations: "registrations"
  }

  resources :users

  resources :appointments do
    resources :notes
  end

  get 'user_photo' => "appointments#user_photo"
  get 'disease_photo' => "appointments#disease_photo"
  get 'archives' => "appointments#archives"

  root 'users#index'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base

  validates :date, presence: true
  validates :status, presence: true
  mount_uploader :cover, CoverUploader


  belongs_to :patient, class_name: "User"
  belongs_to :doctor, class_name: "User"
  has_many :notes, dependent: :destroy
  has_many :images, as: :imagable

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

  before_action :authenticate_user!

  def index
    @my_apps = Appointment.where(doctor_id: current_user.id).paginate(:page => params[:page], :per_page => 5) if current_user.doctor?
    @my_apps = Appointment.where(patient_id: current_user.id).paginate(:page => params[:page], :per_page => 5) if current_user.patient?
  end

  def user_photo
    @all_users_pics = User.all.where.not(cover: nil)
  end

  def disease_photo
    @all_disease_pics = Appointment.all.where.not(cover: nil)
  end

  def archives
    # show past appointment records which are 10 years older
    
    time_range = (Time.now - 10.year)..Time.now
    @past_appointments = Appointment.all.where(date: time_range).paginate(:page => params[:page], :per_page => 5)
  end

  def new
    @appointment = Appointment.new
    @note = Note.new

    @all_doctors = User.doc_list          #Get all doctors
    @all_patients = User.pat_list         #Get all patients
  end

  def create
    @appointment = Appointment.create(appointment_params)
    @note = @appointment.notes.create(notes_params)
    @note.user_id = current_user.id
    if current_user.patient?
      @appointment.patient_id = current_user.id
    else
      @appointment.doctor_id = current_user.id
    end

    if @appointment.save && @note.save
      flash[:notice] = "Appointment Created successfully!"
      redirect_to appointments_path
    else
      flash[:alert] = "Error creating appointment"
      render 'new'
    end
  end

  def show
    @appointment = Appointment.find(params[:id])
    @note = Appointment.last.notes
    curr_id = current_user.id
    @my_notes = Note.where('user_id = ?', curr_id)
  end


  def edit
    @appointment = Appointment.find(params[:id])
    @note = @appointment.notes.last
    @all_doctors = User.doc_list
    @all_patients = User.pat_list
  end

  def update
    @appointment = Appointment.find(params[:id])

    if @appointment.update(appointment_params) && @appointment.notes.last.update(notes_params)
      flash[:notice] = "Appointments updated"
      redirect_to appointments_path
    else
      render 'edit'
    end
  end

  def destroy

    @appointment = Appointment.find(params[:id])
    if @appointment.destroy
      flash[:notice] = "Deleted successfully!"
      redirect_to appointments_path
    else
      flash[:alert] = "Unable to delete"
    end
  end

  private

    def appointment_params
      params.require(:appointment).permit(:date, :status, :doctor_id, :patient_id, :cover)
    end

    def notes_params
      params[:appointment].require(:notes).permit(:description)
    end

end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<%= form_for (@appointment) do |f| %>

  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{ pluralize(@appointment.errors.count, "error") } prohibited this post from being saved:" %>
      </h2>
      <ul>
        <% @appointment.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
          <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :Appointment_With %><br/>

    <% if current_user.patient? %>
      <%= f.collection_select(:doctor_id, @all_doctors, :id, :first_name) %>
    <% else %>
      <%= f.collection_select(:patient_id, @all_patients, :id, :first_name) %>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :Date %><br />
    <%= f.datetime_select :date, start_year: 1990 %>
  </div>

  <div class="field">
    <%= f.label :Status %><br />
    <%= f.text_field :status %>
  </div>

  <div class="field">
    <%= f.fields_for :notes do |field| %>
        <%= field.label "Cause" %><br>
        <%= field.text_area :description %>
    <% end %>
  </div>

  <div class="image-field">
    <% if current_user.patient? %>
      <div class="field">
        <%= f.label :Upload_Image %>
        <%= f.file_field :cover %>
      </div>
    <% end %>
  </div>


  <div class = "button">
    <%= f.submit "Add Appointment" %>
  </div>

<% end %>

app/views/appointments/archives.html.erb
<!DOCTYPE html>
<head>
  <link rel="stylesheet" type="text/css" href="mystyle.css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:800" rel="stylesheet">
</head>
<body>
      <h1 class="text-left">Showing Appointments for past 10 years</h1>

      <div class="div-table">
        <div class="tr">
          <div class="tc"><u><b>Date</b></u></div>
          <div class="tc"><u><b>Name</b></u></div>
          <div class="tc"><u><b>Status</b></u></div>
          <div class="tc"><u><b>Show</b></u></div>
          <div class="tc"><u><b>Edit</b></u></div>
          <div class="tc"><u><b>Delete</b></u></div>
        </div>
        <% @past_appointments.each do |apps| %>
        <div class="tr">
            <div class="tc"> <%= apps.date.to_formatted_s(:long) %></div>
            <% if current_user.doctor? %>
              <div class="tc"> <%= apps.patient.first_name  %>
                               <%= apps.patient.last_name %> ( Patient )
              </div>
            <% else %>
              <div class="tc"> <%= apps.doctor.first_name  %>
                               <%= apps.doctor.last_name %> ( Doctor )
              </div>
            <% end %>
            <div class="tc"> <%= apps.status %></div>
            <div class="tc"> <%= link_to "Show", appointment_path(apps) %></div>
            <div class="tc"><%= link_to "Edit", edit_appointment_path(apps) %></div>
            <div class="tc">
              <%= link_to appointment_path(apps) , method: :delete, data: {confirm: "Hey, Are you sure?"} do %>
                Delete
              <% end %>
            </div>
        </div>
        <% end %>
      </div>

      <div class="paginate-field">
        <%= will_paginate @past_appointments  %>
      </div>
</body>
</html>

app/views/appointments/disease_photo.html.erb
<!DOCTYPE html>
<head>
  <link rel="stylesheet" type="text/css" href="mystyle.css">
</head>
<body>
  <div class="div-table">
    <div class="tr">
      <div class="tc"><u><b>Image</b></u></div>
      <div class="tc"><u><b>Date of Appointment</b></u></div>
      <div class="tc"><u><b>Doctor Name</b></u></div>
      <div class="tc"><u><b>Patient Name</b></u></div>
    </div>
    <% @all_disease_pics.each do |app| %>
    <div class="tr">
        <div class="tc"><%= image_tag (app.cover.url) if app.cover? %></div>
        <div class="tc"><%= app.date.to_formatted_s(:long) %></div>
        <div class="tc"><%= app.doctor.first_name %> <%= app.doctor.last_name %></div>
        <div class="tc"><%= app.patient.first_name %></div>
    </div>
    <% end %>
  </div>
</body>
</html>

app/views/appointments/edit.html.erb
<h1>Edit Appointment Form</h1>
<%= render 'form' %>

app/views/appointments/index.html.erb
<!DOCTYPE html>

  <head>
    <link rel="stylesheet" type="text/css" href="mystyle.css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:800" rel="stylesheet">
  </head>

  <body>

    <h1 class="text-left">
      <u>Appointment List</u>
    </h1>


    <div class="field">
      <h4>Hi, <%= current_user.first_name %> <%= current_user.last_name %></h4>
    </div>

    <div class="field">
      <h4>e-mail: <%= current_user.email %></h4>
    </div>

    <div class="image-container">
      <%= image_tag(current_user.cover.url) if current_user.cover? %>
    </div><br><br>


    <div class="div-table">
        <div class="tr">
          <div class="tc"><u><b>Date</b></u></div>
          <div class="tc"><u><b>Name</b></u></div>
          <div class="tc"><u><b>Status</b></u></div>
          <div class="tc"><u><b>Show</b></u></div>
          <div class="tc"><u><b>Edit</b></u></div>
          <div class="tc"><u><b>Delete</b></u></div>
        </div>
        <% @my_apps.each do |apps| %>
        <div class="tr">
            <div class="tc"> <%= apps.date.to_formatted_s(:long) %></div>
            <% if current_user.doctor? %>
              <div class="tc"> <%= apps.patient.first_name  %>
                               <%= apps.patient.last_name %> ( Patient )
              </div>
            <% else %>
              <div class="tc"> <%= apps.doctor.first_name  %>
                               <%= apps.doctor.last_name %> ( Doctor )
              </div>
            <% end %>
            <div class="tc"> <%= apps.status %></div>
            <div class="tc"> <%= link_to "Show", appointment_path(apps) %></div>
            <div class="tc"><%= link_to "Edit", edit_appointment_path(apps) %></div>
            <div class="tc">
              <%= link_to appointment_path(apps) , method: :delete, data: {confirm: "Hey, Are you sure?"} do %>
                Delete
              <% end %>
            </div>
        </div>
        <% end %>
      </div>

      <div class="paginate-field">
        <%= will_paginate @my_apps  %>
      </div>

  </body>
</html>

app/views/appointments/new.html.erb
<h1>New Appointment Form</h1>
<%= render 'form' %>

app/views/appointments/show.html.erb
<div class="button">
    <%= link_to "Back To My Home", appointments_path %>
</div><br>

<div class="field">
  <div><h3>Appointment Date: </h3>
    <%= @appointment.date.to_formatted_s(:long) %>
  </div>
</div>

<div class="field">
  <div><h3>Appointment Status: </h3>
    <%= @appointment.status %>
  </div>
</div>

<% if current_user.patient? %>
  <div class="image-field">
      <div><strong><h4>Appointment Image:</h4></strong></div>
      <%= image_tag (@appointment.cover.url) if @appointment.cover? %>
  </div>
<% end %>

<div class="field">
  <h3><u>All Notes:</u></h3>
  <% @my_notes.each do |n| %>
    <div class="field">
      <div><h5>Description: </h5>
        <%= n.description %>
      </div>
    </div>
  <% end %>
</div>
<br>

app/views/appointments/user_photo.html.erb
<!DOCTYPE html>
<head>
  <link rel="stylesheet" type="text/css" href="mystyle.css">
</head>
<body>
  <div class="div-table">
    <div class="tr">
      <div class="tc"><u><b>Image</b></u></div>
      <div class="tc"><u><b>Name</b></u></div>
    </div>
    <% @all_users_pics.each do |user| %>
    <div class="tr">
        <div class="tc"><%= image_tag (user.cover.url) if user.cover? %></div>
        <div class="tc"><%= user.first_name %></div>
    </div>
    <% end %>
  </div>
</body>
</html>