config/routes.rb
Rails.application.routes.draw do

  get '/:token/confirm_email/', :to => "users#confirm_email", as: 'confirm_email'

  devise_for :users , controllers: {
    registrations: "registrations"
  }

  resources :users

  resources :appointments do
    resources :notes
  end

  get 'user_photo' => "appointments#user_photo"
  get 'disease_photo' => "appointments#disease_photo"
  get 'archives' => "appointments#archives"

  root 'users#index'

end

app/views/layouts/_navigation.html.erb
<!DOCTYPE html>
<html>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">

    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'My Appointments', appointments_path %></li>
        <% if user_signed_in? %>
        <!--This block is only visible to signed in admins -->
          <li><%= link_to 'Add New Appointment', new_appointment_path %></li>
          <li><%= link_to 'My Account', edit_user_registration_path  %></li>
          <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
        <!-- The block ends here -->
        <% else %>
          <li><%= link_to 'Login', new_user_session_path  %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
</body>
<html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hospital Management System</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <body>

    <div class="page-container">
      <div class="top-navigation">
        <%= render "layouts/navigation" %>
      </div>

      <div class="sidenav">
        <a href="#">About</a>
        <a href="#">Contact</a>
        <div class="user-images">
          <%= link_to 'Get all Users', user_photo_path %>
        </div>
        <div class="appointment-images">
          <%= link_to 'Get all Disease Images', disease_photo_path %>
        </div>
        <div class="appointment-images">
          <%= link_to 'Archives', archives_path %>
        </div>
      </div>

      <div class="main-body">
        <div><p class="notice"><%= notice %></p></div>
        <div><p class="alert"><%= alert %></p></div>
        <%= yield %>
      </div>
    </div>

  </body>
</html>